#! /bin/sh

# refresh colourscheme
feh --bg-fill "${HOME}/.config/wallpapers/oktomi-jaya-2EzSfkFLOmw-unsplash.jpg" &
wal -R &

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color6"
bspc config active_border_color "$color6"
bspc config focused_border_color "$color1"

# kill and start background processes
killall sxhkd ; sxhkd &
killall dunst ; dunst &
#killall compton ; compton &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
#bspc config ignore_ewmh_fullscreen enter

# window rules
bspc rule -a Signal desktop='^3'
bspc rule -a Zathura state=tiled
