theme = "ingrid2"

[editor]
line-number = "relative"
color-modes = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "version-control", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[editor.gutters]
layout = ["diff", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 1

[editor.soft-wrap]
enable = true

[keys.normal]
";" = "command_mode"
