# Author : Ingrid Rebecca Abraham <git@ingrids.email>

"attribute" = "green"
"keyword" = { fg = "red", modifiers = ["bold"] }
"keyword.directive" = "dark-green"
"keyword.function" = "cyan"
"keyword.storage.modifier" = { fg = "red", modifiers = ["italic"] }
"namespace" = "dark-cyan"
"punctuation" = "dark-magenta"
"punctuation.delimiter" = "dark-magenta"
"operator" = { fg = "red", modifiers = ["bold"] }
"special" = "magenta"
"variable.other.member" = "cyan"
"variable" = "dark-cyan"
"variable.parameter" = "cyan"
"type" = "green"
"type.builtin" = "green"
"constructor" = { fg = "green", modifiers = ["bold"] }
"function" = { fg = "cyan", modifiers = ["bold"] }
"function.macro" = { fg = "magenta", modifiers = ["bold", "italic"] }
"function.builtin" = "cyan"
"comment" = "blue"
"variable.builtin" = "yellow"
"constant" = "yellow"
"constant.builtin" = "yellow"
"string" = "red"
"constant.numeric" = "red"
"constant.character.escape" = { fg = "red", modifiers = ["bold"] }
"label" = "magenta"

"module" = "dark-cyan"

# TODO
"markup.heading" = "blue"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = "cyan"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"

"ui.background" = { bg = "white" }
"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "red", modifiers = ["bold"] }
"ui.cursorline" = { bg = "light-hl" }
"ui.statusline" = { fg = "black", bg = "light-hl" }
"ui.statusline.inactive" = { fg = "dark-blue", bg = "light-hl" }
"ui.statusline.normal" = { fg = "white", bg = "dark-blue", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "white", bg = "dark-magenta", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "white", bg = "dark-green", modifiers = ["bold"] }
"ui.popup" = { fg = "dark-blue", bg = "light-hl" }
"ui.window" = { bg = "dark-hl" }
"ui.help" = { bg = "dark-hl", fg = "black" }
"ui.virtual.indent-guide" = "light-hl"

"ui.text" = { fg = "dark-blue" }
"ui.text.focus" = { fg = "black", modifiers= ["bold"] }
"ui.virtual.whitespace" = "blue"
"ui.virtual.ruler" = { bg = "light-hl" }

"ui.selection" = { bg = "light-hl" }
"ui.cursor.primary" = { bg = "red", fg = "white", modifiers = ["bold"] }
"ui.cursor.match" = { bg = "light-hl", fg = "red", modifiers = ["bold"] }
"ui.menu" = { fg = "dark-blue", bg = "light-hl" }
"ui.menu.selected" = { fg = "red", bg = "light-hl" }

"warning" = "yellow"
"error" = "red"
"info" = "green"
"hint" = "blue"

"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.info" = { underline = { color = "green", style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue", style = "curl" } }

[palette]
light-hl = "#F3EAE9"
red = "#D74E50"
green = "#839A53"
yellow = "#D4A520"
blue = "#A6B6CE"
magenta = "#D68482"
cyan = "#89BEB7"
pink = "#ECC3C2"
dark-hl = "#D8B8B3"
dark-red   = "#832426"
dark-green = "#6F873E"
dark-yellow = "#C39104"
dark-blue = "#7B91B3"
dark-magenta = "#C97270"
dark-cyan = "#63A098"
other-yellow = "#F2CC60"

black = "#250E07"
white = "#FFFCFD"
gray = "#BBBBBB"
